### ISSUE TITLE
Use of StaticQuery insted of dynamic

### ISSUE THREAD

**Issue by lisandropat** [Vagr9K/gatsby-advanced-starter#104]
When I run `gatsby develop` it builds but I get this error in the console:

> The GraphQL query in the non-page component "D:/src/gatsby-advanced-starter/src/templates/landing.jsx" will not be run.
> Exported queries are only executed for Page components. It's possible you're
> trying to create pages in your gatsby-node.js and that's failing for some
> reason.
> 
> If the failing component(s) is a regular component and not intended to be a page
> component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
> instead of exporting a page query.
> 
> If you're more experienced with GraphQL, you can also export GraphQL
> fragments from components and compose the fragments in the Page component
> query and pass data down into the child component — https://graphql.org/learn/queries/#fragments

Should dynamic queries be replaced with static queries?

**Comment by Vagr9K** [comment]
The warning is actually misleading here.

We have two templates that can be used for the landing page:
- [`landing.jsx`](https://github.com/Vagr9K/gatsby-advanced-starter/blob/master/src/templates/landing.jsx) which has no paging
- [`listing.jsx`](https://github.com/Vagr9K/gatsby-advanced-starter/blob/master/src/templates/listing.jsx) which has paging

By default the second option is selecting in `data/SiteConfig.js` as a landing page and provides paging.
Due to this Gatsby things that there is an issue with the non-default `landing.jsx` since its queries aren't being invoked.
