### ISSUE TITLE
[Suggestion] Add Storybook for development

### ISSUE THREAD

**Issue by rdricco** [Vagr9K/gatsby-advanced-starter#23]
As title says, i think storybook could be great if added to your starter.

**Comment by Vagr9K** [comment]
After investigating the Storybook implementations that work with Gatsby, it's clear that:

* It's buggy. For example see https://github.com/gatsbyjs/gatsby/issues/4300. Some version of babel-loader work, others don't
* Differences of webpack/babel versions between Gatsby and Sotrybook make things much harder
* Complexity introduced by adding support for Storybook isn't worth it, especially with Gatsby v2 being right around the corner

After thinking for a while I've decided to not add Storybook support since it will cause long term maintenance issues.

Still, thank you for bringing this up.
