### ISSUE TITLE
Make this project the parent of Material starter

### ISSUE THREAD

**Issue by Scot3004** [Vagr9K/gatsby-advanced-starter#44]
I think the codebase of this and https://github.com/Vagr9K/gatsby-material-starter could be shared if you separate the gastby specific code, and the material desing code, by some hoc tecniques

**Comment by Vagr9K** [comment]
It has been tried in the past.
Unfortunately Gatsby starter architecture and differences in feature sets  of the starters create major maintainability issues.

> separate the gastby specific code, and the material desing code
Gatsby had plans for adding theming support that would replace/enhance starters when it comes to design aspects.
Whenever this feature arrives it will make more sense to use it's abilities instead of trying to decouple use case specific code.

**Comment by Scot3004** [comment]
Agree
